financeweb/appfinance/urls.py
from django.conf.urls import patterns, include, url
import views
urlpatterns = patterns(
    '',
    #url(r'^signin/$', views.SignInView.as_view(), name="signin"),
    url(r'^getexaminemessages/$', views.ExamineMessages.as_view(), name="getexaminemessages"),
    url("^$", views.Index.as_view(), name="home"),
    url("^selffinance/$", views.SelfFinance.as_view(), name="selffinance"),
    url("^makefinance/$", views.MakeFinance.as_view(), name="makefinance"),
    url(r'^examineamekshow/$', views.ExaminemakeShow.as_view(), name="examinemakeshow"),
    url(r'^examineshow/$', views.ExamineDate.as_view(), name="examineshow"),
    url(r'^examinehistoryshow/$', views.ExamineHistroyDate.as_view(), name="examinehistoryshow"),
)

financeweb/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template
from financeweb.apphome import views
import os
from settings import PROJECT_ROOT

admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

urlpatterns += patterns('',

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    #url("^$", direct_to_template, {"template": "index.html"}, name="home"),
    url(r'^images/(?P<path>.*)$',
        'django.views.static.serve',
        {"document_root": os.path.join(
            PROJECT_ROOT, "templates/static/images").replace("\\", "/")}),
    url(r'^font/(?P<path>.*)$',
        'django.views.static.serve',
        {"document_root": os.path.join(
            PROJECT_ROOT, "templates/static/font").replace("\\", "/")}),
    url(r'^stylesheets/(?P<path>.*)$',
        'django.views.static.serve',
        {"document_root": os.path.join(
            PROJECT_ROOT, "templates/static/stylesheets").replace("\\", "/")}),
    url(r'^css/(?P<path>.*)$',
        'django.views.static.serve',
        {"document_root": os.path.join(
            PROJECT_ROOT, "templates/static/css").replace("\\", "/")}),
    url(r'^javascripts/(?P<path>.*)$',
        'django.views.static.serve',
        {"document_root": os.path.join(
            PROJECT_ROOT, "templates/static/javascripts").replace("\\", "/")}),
    url(r'^bootstrap/(?P<path>.*)$',
        'django.views.static.serve',
        {"document_root": os.path.join(
            PROJECT_ROOT, "templates/static/bootstrap").replace("\\", "/")}),
    ("^sign/", include('financeweb.appsign.urls')),
    ("^finance/", include('financeweb.appfinance.urls')),
    url("^$", views.Index.as_view(), name="index"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

financeweb/appfinance/models.py
from django.db import models

# Create your models here.

financeweb/apphome/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
# Create your models here.
class Finance(models.Model):
    ACCOUNT_CHOICE = (
        ('-1', _(u"出账")),
        ('1', _(u"入账"))
    )
    startperson = models.ForeignKey(User)
    maneycount = models.DecimalField(max_digits=8,decimal_places=2)
    financename = models.CharField(_('name'), max_length=80)
    financeintro = models.CharField(_('intro'), max_length=80)
    examineperson = models.ManyToManyField(User, through="FinanceUser", null=True, blank=True, related_name="examineperson", verbose_name=_("users"))
    financetype = models.CharField(_('financetype'), max_length=80, choices=ACCOUNT_CHOICE)
    status = models.IntegerField(_("Status"), default=0) #0审批中，1审批通过，-1审批驳回
class FinanceUser(models.Model):
    finance = models.ForeignKey(Finance)
    user = models.ForeignKey(User)
    status = models.BooleanField(_("examinestatus"), default=False)
    examinedate = models.DateTimeField(auto_now_add=True)
    examineinfo = models.CharField(_("examineinfo"), max_length=80, null=True, blank=True)

financeweb/appfinance/views.py
# -*- coding:utf-8 -*-
# Create your views here.
from django.utils.translation import ugettext as _
from django.views.generic.base import View
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from financeweb.apphome import models
from django.core.urlresolvers import reverse
from financeweb.apphome.views import auth_required

class ExamineMessages(View):
    model = models.Finance
    def get(self, request, *args, **kwargs):
        financelist = self.model.objects.filter(status=0)
        count=0
        for finance in financelist:
            if request.user not in finance.examineperson.all():
                count+=1
        return HttpResponse(count)

class Index(View):
    template_name = 'appfinance/index.html'
    @auth_required
    def get(self, request):
        user = request.user
        username = user.username
        objects = models.Finance.objects.all()
        return render_to_response(self.template_name, {'username': username, 'objects':objects})

class SelfFinance(View):
    template_name = 'appfinance/selffinance.html'
    @auth_required
    def get(self, request):
        user = request.user
        username = user.username
        objects = models.Finance.objects.filter(startperson=user)
        return render_to_response(self.template_name, {'username': username, 'objects':objects})
        
class ExamineDate(View):
    template_name = 'appfinance/examinedatashow.html'
    model = models.Finance
    @auth_required
    def get(self, request, *args, **kwargs):
        username = request.user.username
        financelist = self.model.objects.filter(status=0)
        objects = []
        for finance in financelist:
            if request.user not in finance.examineperson.all():  
                objects.append(finance)
        return render_to_response(self.template_name, {'username': username,'objects':objects})

class ExamineHistroyDate(View):
    template_name = 'appfinance/examinehistoryshow.html'
    @auth_required
    def get(self, request, *args, **kwargs):
        user = request.user
        objects = user.financeuser_set.all()
        return render_to_response(self.template_name, {'objects':objects})

class ExaminemakeShow(View):
    template_name = 'appfinance/examinemakeshow.html'
    @auth_required
    def get(self, request, *args, **kwargs):
        financepk = request.GET.get('finance', '')
        operate = request.GET.get('operate', '')
        if financepk:
            try:
                financeobject = models.Finance.objects.get(pk=int(financepk))
                return render_to_response(self.template_name, {'financeobject':financeobject,'operate':operate})
            except:
                return HttpResponse(u'数据错误，申请单不存在')
        else:
            return HttpResponse(u'数据错误，申请单编号不能为空')
    def post(self, request, *args, **kwargs):
        user = request.user
        financepk = request.POST.get('finance', '')
        operate = request.POST.get('operate', '')
        info = request.POST.get('info', '')
        financeobject=models.Finance.objects.get(pk=int(financepk))
        if operate:
            status = True 
        else:
            status = False 
        if models.FinanceUser.objects.filter(user=user, finance=financeobject): 
            financeuser=models.FinanceUser.objects.get(user=user, finance=financeobject)
            financeuser.status = status
            financeuser.examineinfo = info
            financeuser.save()
            if  len(models.FinanceUser.objects.filter(finance=financeobject,status=True)) == 4:
                    financeobject.status = 1 
            elif models.FinanceUser.objects.filter(finance=financeobject,status=False):
                    financeobject.status = -1 
            else:
                    financeobject.status = 0 
            financeobject.save()
        else:
            financeuser = models.FinanceUser(user=user, finance=financeobject, status=status, examineinfo=info)
            financeuser.save()
            if  len(models.FinanceUser.objects.filter(finance=financeobject,status=True)) == 4:
                    financeobject.status = 1 
            elif models.FinanceUser.objects.filter(finance=financeobject,status=False):
                    financeobject.status = -1 
            else:
                    financeobject.status = 0 
            financeobject.save()
        return HttpResponse(u'审批成功')

class MakeFinance(View):
    template_name="appfinance/makefinance.html"
    @auth_required
    def get(self, request, *args, **kwargs):
        financetypelist=["-1"]
        financepk = request.GET.get('financepk','')
        if financepk:
            try:
                financeobject = models.Finance.objects.get(pk=int(financepk))
                financename = financeobject.financename
                financeinfo = financeobject.financeintro
                financecount = financeobject.maneycount
                financetype = financeobject.financetype
            except:
                financename = ""
                financeinfo = ""
                financecount = ""
                financetype = "-1"
        else:
            financename = ""
            financeinfo = ""
            financecount = ""
            financetype = "-1"
        context={
            'financepk':financepk,
            'financename':financename,
            'financeinfo':financeinfo,
            'financetypelist':financetypelist,
            'financetype':financetype,
            'financecount':financecount

        }
        return render_to_response(self.template_name,context) 
    @auth_required
    def post(self, request, *args, **kwargs):
        financename = request.POST.get('financename','')
        financeinfo = request.POST.get('financeinfo','')
        financetype = request.POST.get('financetype','')
        financecount = request.POST.get('financecount','')
        financepk = request.POST.get('financepk','')
        try:
            float(financecount)
        except:
            return HttpResponse(u"金额必需是浮点数或整数")
        if financename and financeinfo and financetype and financecount:
            user = request.user
            if financepk:
                newobject = models.Finance.objects.get(pk=int(financepk))
                financeuserlist = newobject.financeuser_set.all()
                for financeuser in financeuserlist:
                    financeuser.delete()
                newobject.maneycount = financecount
                newobject.financename = financename
                newobject.financeintro = financeinfo
                newobject.financetype = financetype
                newobject.status = 0 
            else:
                newobject = models.Finance(startperson=user, maneycount=financecount, financename=financename, financeintro=financeinfo, financetype=financetype)
            newobject.save()
            return HttpResponseRedirect(reverse("home"))
        else:
            return HttpResponse(u'名称:'+financename+u' 描述:'+financeinfo+u'类型:'+financetype+u'金额:'+financecount+u" 都不能为空,且金额为浮点型")

financeweb/templates/appfinance/examinedatashow.html
{% extends "base.html" %}
{% block "contents" %}
<table class="table table-striped table-bordered table-condensed table-hover">
<tr><th>名称</th><th style="width:20%;">描述</th><th>申请人</th><th>金额(元)</th><th style="width:20%;">操作</th></tr>
{% if not objects %}
<tr><td colspan="5">没有需要审批的数据!</td></tr>
{% endif %}
{% for object in objects %}
<form id="examineform{{object.pk}}">
<input type="text" style="display:none;" name="finance" value="{{object.pk}}"/>
<tr>
    <td>{{object.financename}}</td>
    <td>{{object.financeintro}}</td>
    <td>{{object.startperson.username}}</td>
    <td>{{object.maneycount}}</td>
    <td><input type="button" name="operate" class="btn btn-small green" style="width:58px;" onclick="ajax_to_dialog('examineform{{object.pk}}','{% url "examinemakeshow" %}','通过申请单',1)" value="通过"/>&#160;
        <input type="submit" name="operate" class="btn btn-small red" style="width:58px;" onclick="return ajax_to_dialog('examineform{{object.pk}}','{% url "examinemakeshow" %}','驳回申请单')" value="驳回"/></td>
</tr>
</form>
{% endfor %}
<tr><td colspan="5"><a href="{% url 'examinehistoryshow' %}">查看审批历史数据</a></td></tr>
</table>
{% endblock %}

financeweb/templates/appfinance/examinehistoryshow.html
{% extends "base.html" %}
{% block "contents" %}
<table class="table table-striped table-bordered table-condensed table-hover">
<tr>
    <th>名称</th>
    <th style="width:20%;">描述</th>
    <th>申请人</th>
    <th>金额(元)</th>
    <th style="">审核结果</th>
    <th>审核意见</th>
    <th>审核日期</th>
</tr>
{% if not objects %}
<tr><td colspan="7">没有审批历史数据!</td></tr>
{% endif %}
{% for object in objects %}
<tr>
    <td>{{object.finance.financename}}</td>
    <td>{{object.finance.financeintro}}</td>
    <td>{{object.finance.startperson.username}}</td>
    <td>{{object.finance.maneycount}}</td>
    <td>{% if object.status%}通过{% else%}驳回{% endif %}</td>
    <td>{{object.examineinfo}}</td>
    <td>{{object.examinedate}}</td>
</tr>
</form>
{% endfor %}
<tr><td colspan="7"><a href="{% url 'examineshow' %}">查看需审批数据</a></td></tr>
</table>
{% endblock %}

financeweb/templates/appfinance/examinemakeshow.html
<form id="dialog-form">
<input type="text" value="{{financeobject.pk}}" name="finance" style="display:none;"/>
<input type="text" value="{{operate}}" name="operate" style="display:none;"/>
<table class="table table-striped table-bordered table-condensed table-hover" >
<tr><td>申请单名称：</td><td>{{financeobject.financename}}</td></tr>
<tr><td>原因：</td><td><textarea name="info"></textarea></td></tr>
</table>
</form>

financeweb/templates/appfinance/index.html
{% extends "base.html" %}
{% block "righttop"%}财务管理>>财务总览{% endblock %}
{% block "contents" %}
<table class="table table-striped table-bordered table-condensed table-hover">
<tr><th>名称</th><th>描述</th><th>申请人</th><th>金额(元)</th><th>类型</th><th style="width:10%">审批状态</th><th style="width:35%">审批信息</th></tr>
{% for object in objects %}
<tr>
    <td>{{object.financename}}</td>
    <td>{{object.financeintro}}</td>
    <td>{{object.startperson.username}}</td>
    <td>{{object.maneycount}}</td>
    <td>{{object.get_financetype_display}}</td>
    <td>{%if object.status == 0 %}<font color="#ff8330">审批中</font>{%else%}{%if object.status == 1 %}<font color="#63a822">成功</font>{%else%}<font color="#db3535">驳回</font>{% endif %}{%endif%}</td>
    <td>
        <table class="table table-striped table-bordered table-condensed table-hover">
       <tr><td>审批人</td><td>审批结果</td><td>审批意见</td><td>审批时间</td></tr>
        {% for person_set in object.financeuser_set.all %}
           {% with person=person_set.user%} 
            <tr><td>{{person.username}}</td><td>{%if person_set.status %}<font color="#63a822">通过</font>{% else %}<font color="#db3535">驳回</font>{% endif %}</td><td>{{person_set.examineinfo}}</td><td>{{person_set.examinedate|date:"F j,Y f"}}</td></tr>
           {% endwith %}
        {% endfor%}
        </table>
    </td>
</tr>
{% endfor %}
</table>
{% endblock %}

financeweb/templates/appfinance/makefinance.html
{% extends "base.html" %}
{% block "contents" %}
<form method="post">
<input name="financepk" value="{{financepk}}" type="text" style="display:none;"/>
<table class="table table-striped table-bordered table-condensed table-hover" style="width:80%;margin:auto;margin-top:10px;">
<tr><td>名称</td><td><input type="text" name="financename" value="{{financename}}"style="margin-bottom:0px;"/></td></tr>
<tr><td>描述</td><td><textarea name="financeinfo" style="margin-bottom:0px;">{{financeinfo}}</textarea></td></tr>
<tr><td>类型</td><td>
                <select name="financetype" value="0" style="width:206px;margin-bottom:0px;">
                {% for onetype in financetypelist %}
                <option value="{{onetype}}"{% if onetype == financetype %}selected="selected"{% endif %}>出账</option>
                {% endfor %}
                </select>
                </td>
</tr>
<tr><td>金额(元)</td><td><input type="text" name="financecount"style="margin-bottom:0px;"value="{{financecount}}"/></td></tr>
<tr><td colspan="2"><input type="reset" class="btn"value="重置" style="width:100px;margin-left:300px;"/>&#160;&#160;&#160;&#160;<input type="submit" class="btn" value="提交" style="width:100px;"/></td></tr>
</table>
</form>
{% endblock %}

financeweb/templates/appfinance/selffinance.html
{% extends "base.html" %}
{% block "contents" %}
<table class="table table-striped table-bordered table-condensed table-hover">
<tr><th>名称</th><th>描述</th><th>申请人</th><th>金额(元)</th><th>类型</th><th style="width:10%">审批状态</th><th style="width:35%">审批信息</th></tr>
{% for object in objects %}
<tr>
    <td>{{object.financename}}</td>
    <td>{{object.financeintro}}</td>
    <td>{{object.startperson.username}}</td>
    <td>{{object.maneycount}}</td>
    <td>{{object.get_financetype_display}}</td>
    <td>{%if object.status == 0 %}<font color="#ff8330">审批中</font>{%else%}{%if object.status == 1 %}<font color="#63a822">成功</font>{%else%}<font color="#db3535">驳回</font><a href="{% url 'makefinance' %}?financepk={{object.pk}}">重新提交</a>{% endif %}{%endif%}</td>
    <td>
        <table class="table table-striped table-bordered table-condensed table-hover">
       <tr><td>审批人</td><td>审批结果</td><td>审批意见</td><td>审批时间</td></tr>
        {% for person_set in object.financeuser_set.all %}
           {% with person=person_set.user%} 
            <tr><td>{{person.username}}</td><td>{%if person_set.status %}<font color="#63a822">通过</font>{% else %}<font color="#db3535">驳回</font>{% endif %}</td><td>{{person_set.examineinfo}}</td><td>{{person_set.examinedate|date:"F j,Y f"}}</td></tr>
           {% endwith %}
        {% endfor%}
        </table>
    </td>
</tr>
{% endfor %}
</table>
{% endblock %}